edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 60
struct_variant_width = 60
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
normalize_comments = false
remove_nested_parens = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
