[package]
name = "ling-mir"
version = "2030.0.0"
edition = "2021"
authors = ["Ling Lin <taellinglin@gmail.com>", "Sanny Lin <SannyLing53@gmail.com>"]
description = "Ling MIR - Mid-level Intermediate Representation for codegen backends"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taellinglin/ling"

[dependencies]
ling-core = { path = "../ling-core", version = "2030.0.0" }
ling-ast  = { path = "../ling-ast",  version = "2030.0.0" }
anyhow = "1.0"
rustc-hash = "2.0"

