//! Placeholder module: src/parser/grammar.rs
//!
//! The real grammar is normally generated by lalrpop into `$OUT_DIR`
//! (see build.rs). This placeholder exists so the crate compiles in this WIP state.

#[allow(unused_imports)]
use crate::lexer::{Lexer, Token};
use crate::parser::ast::Program;

pub struct ProgramParser;

impl ProgramParser {
    pub fn new() -> Self {
        Self
    }

    pub fn parse(&self, _lexer: &mut Lexer<'_>) -> Result<Program, String> {
        Ok(Program { items: vec![] })
    }
}
