[package]
name = "ling-ast"
version = "2030.0.6"
edition = "2021"
authors = ["Ling Lin <taellinglin@gmail.com>", "Sanny Lin <SannyLing53@gmail.com>"]
description = "Abstract Syntax Tree types for the Ling language"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/taellinglin/ling"

[dependencies]
ling-core    = { workspace = true }
ling-lex     = { workspace = true }
lalrpop-util = "0.22"
serde        = { version = "1.0", features = ["derive"] }

[lib]
name = "ling_ast"
path = "src/lib.rs"
