[package]
name = "ling-py"
version = "2030.0.7"
description = "Python bindings for ling-audio, ling-physics, and ling-net"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taellinglin/ling"
homepage = "https://ling-lang.org"
authors = ["Ling Lin <taellinglin@gmail.com>", "Sanny Lin <SannyLing53@gmail.com>"]
