[package]
name = "ling-lex"
version = "2030.0.0"
edition = "2021"
authors = ["Ling Lin <ling@ling-lang.org>"]
description = "Lexical analysis and polyglot tokenization for Ling"

[dependencies]
ling-core = { path = "../ling-core" }
unicode-script = "0.5"
unicode-normalization = "0.1"
logos = "0.13"
phf = { version = "0.11", features = ["macros"] }

